version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: cameroncrow
      POSTGRES_DB: sdc
      DATABASE_URL: postgres://cameroncrow:@localhost:5432/sdc
    volumes:
      - ./my-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'server'
    environment:
      DB_HOST: host.docker.internal
      DB_USER: cameroncrow
      DB_PASS: password
    ports:
      - '3001:3001'